name: Supabase Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "supabase/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "supabase/**"

jobs:
  supabase:
    name: Test & Lint Supabase
    runs-on: ubuntu-latest
    env:
      GOOGLE_AUTH_CLIENT_ID: MY_TEST_VAR
      GOOGLE_AUTH_SECRET: MY_TEST_VAR
      FACEBOOK_CLIENT_AUTH_ID: MY_TEST_VAR
      FACEBOOK_SECRET_AUTH: MY_TEST_VAR
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase Start
        run: supabase start
      - name: Supabase Lint
        run: supabase db lint -s public
      - name: Setup supabase testing
        run: |
          psql -v ON_ERROR_STOP=1 -U postgres -d postgres -h localhost -p 54322 -f .github/workflows/setup-testing.sql
        env:
          PGPASSWORD: postgres
      - name: Run Tests
        run: supabase test db
